name: Backend Application CI/CD
on:
  push:
    branches:
      - main

env:
  DEV_ARM_SUBSCRIPTION_ID: ${{ secrets.DEV_ARM_SUBSCRIPTION_ID }}
  DEV_ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  DEV_ARM_CLIENT_ID: ${{ secrets.DEV_ARM_CLIENT_ID }}
  DEV_ARM_CLIENT_SECRET: ${{ secrets.DEV_ARM_CLIENT_SECRET }}

jobs:
  dev-ci:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ env.DEV_ARM_CLIENT_ID }}","clientSecret":"${{ env.DEV_ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.DEV_ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.DEV_ARM_TENANT_ID }}"}'
      
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: moodyscontainer
          containerAppName: meishatestcontainerapp
          resourceGroup: marysha-devwork
          containerAppEnvironment: meishatestconappenv
          ingress: internal
          targetPort: 80
          acrUsername: ${{ secrets.ACR_USERNAME }}
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          imageToDeploy: moodyscontainer.azurecr.io/albumapi:latest
          environmentVariables: ENV1=HI ENV2=WORLD \
                                 ENV3=YO
